-- Create tables
CREATE TABLE IF NOT EXISTS transactions (
	id SERIAL PRIMARY KEY,
	description VARCHAR(255) NOT NULL,
	amount DECIMAL(10,2) NOT NULL,
	category VARCHAR(100) NOT NULL,
	date DATE NOT NULL,
	currency VARCHAR(3) DEFAULT 'BRL',
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_settings (
	id SERIAL PRIMARY KEY,
	currency VARCHAR(3) DEFAULT 'BRL',
	theme VARCHAR(10) DEFAULT 'light',
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	type VARCHAR(50) NOT NULL
);

-- Insert default categories
INSERT INTO categories (name, type) VALUES
	('Salário', 'income'),
	('Alimentação', 'expense'),
	('Transporte', 'expense'),
	('Moradia', 'expense'),
	('Lazer', 'expense'),
	('Saúde', 'expense'),
	('Educação', 'expense'),
	('Outros', 'expense');

-- Create test transaction
INSERT INTO transactions (description, amount, category, date) 
VALUES ('Teste inicial', 100.00, 'Outros', CURRENT_DATE);

-- Tabela de Despesas Fixas
CREATE TABLE IF NOT EXISTS fixed_expenses (
	id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
	user_id UUID REFERENCES auth.users NOT NULL,
	description TEXT NOT NULL,
	amount DECIMAL NOT NULL,
	category TEXT NOT NULL,
	due_day INTEGER NOT NULL,
	notification_days INTEGER DEFAULT 3,
	notes TEXT,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
	
	CONSTRAINT positive_amount CHECK (amount > 0),
	CONSTRAINT valid_due_day CHECK (due_day BETWEEN 1 AND 31),
	CONSTRAINT valid_notification_days CHECK (notification_days >= 0)
);

-- Tabela de Pagamentos de Despesas Fixas
CREATE TABLE IF NOT EXISTS fixed_expense_payments (
	id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
	fixed_expense_id UUID REFERENCES fixed_expenses ON DELETE CASCADE NOT NULL,
	user_id UUID REFERENCES auth.users NOT NULL,
	amount DECIMAL NOT NULL,
	date DATE NOT NULL,
	payment_proof TEXT,
	notes TEXT,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
	
	CONSTRAINT positive_payment_amount CHECK (amount > 0)
);

-- Habilitar RLS
ALTER TABLE fixed_expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE fixed_expense_payments ENABLE ROW LEVEL SECURITY;

-- Políticas para Despesas Fixas
CREATE POLICY "Visualizar próprias despesas fixas"
ON fixed_expenses FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Inserir próprias despesas fixas"
ON fixed_expenses FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Atualizar próprias despesas fixas"
ON fixed_expenses FOR UPDATE USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Deletar próprias despesas fixas"
ON fixed_expenses FOR DELETE
USING (auth.uid() = user_id);

-- Políticas para Pagamentos
CREATE POLICY "Visualizar próprios pagamentos"
ON fixed_expense_payments FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Inserir próprios pagamentos"
ON fixed_expense_payments FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Atualizar próprios pagamentos"
ON fixed_expense_payments FOR UPDATE USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Deletar próprios pagamentos"
ON fixed_expense_payments FOR DELETE
USING (auth.uid() = user_id);

-- Função para atualizar o updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
	new.updated_at = timezone('utc'::text, now());
	return new;
END;
$$ LANGUAGE plpgsql;

-- Trigger para atualizar o updated_at
CREATE TRIGGER update_fixed_expenses_updated_at
BEFORE UPDATE ON fixed_expenses
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Criar tabela de metas financeiras
CREATE TABLE IF NOT EXISTS financial_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    target_amount DECIMAL(10,2) NOT NULL CHECK (target_amount > 0),
    deadline DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Criar índices para metas
CREATE INDEX IF NOT EXISTS financial_goals_user_id_idx ON financial_goals(user_id);
CREATE INDEX IF NOT EXISTS financial_goals_deadline_idx ON financial_goals(deadline);

-- Habilitar RLS para metas
ALTER TABLE financial_goals ENABLE ROW LEVEL SECURITY;

-- Criar políticas de segurança para metas
CREATE POLICY "Usuários podem ver suas próprias metas"
ON financial_goals FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Usuários podem criar suas próprias metas"
ON financial_goals FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Usuários podem atualizar suas próprias metas"
ON financial_goals FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Usuários podem deletar suas próprias metas"
ON financial_goals FOR DELETE
USING (auth.uid() = user_id);

-- Remover políticas existentes da tabela goal_contributions
DROP POLICY IF EXISTS "Usuários podem ver suas próprias contribuições" ON goal_contributions;
DROP POLICY IF EXISTS "Usuários podem inserir suas próprias contribuições" ON goal_contributions;
DROP POLICY IF EXISTS "Usuários podem atualizar suas próprias contribuições" ON goal_contributions;
DROP POLICY IF EXISTS "Usuários podem deletar suas próprias contribuições" ON goal_contributions;

-- Criar tabela de contribuições para metas
CREATE TABLE IF NOT EXISTS goal_contributions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	goal_id BIGINT REFERENCES financial_goals(id) ON DELETE CASCADE,
	user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
	amount DECIMAL(10,2) NOT NULL CHECK (amount > 0),
	date DATE NOT NULL DEFAULT CURRENT_DATE,
	notes TEXT,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Criar índices para melhor performance
CREATE INDEX IF NOT EXISTS goal_contributions_goal_id_idx ON goal_contributions(goal_id);
CREATE INDEX IF NOT EXISTS goal_contributions_user_id_idx ON goal_contributions(user_id);
CREATE INDEX IF NOT EXISTS goal_contributions_date_idx ON goal_contributions(date);

-- Habilitar RLS (Row Level Security)
ALTER TABLE goal_contributions ENABLE ROW LEVEL SECURITY;

-- Criar políticas de segurança
CREATE POLICY "Usuários podem ver suas próprias contribuições"
ON goal_contributions FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Usuários podem inserir suas próprias contribuições"
ON goal_contributions FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Usuários podem atualizar suas próprias contribuições"
ON goal_contributions FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Usuários podem deletar suas próprias contribuições"
ON goal_contributions FOR DELETE
USING (auth.uid() = user_id);
